### ISSUE TITLE
Error with synchronized players?

### ISSUE THREAD

**Issue by bjarteskogoy** [aesculus/denonavpcontrol#21] opened 2022-09-06 09:57 UTC
It seems to me that synchronized players causes an error with the latest version.
Multiple synchronized players which are not connected to a receiver works OK.
A single player connected to receiver works OK.

When synchronizing a player with a connected receiver, playback stops after a few seconds and I find this message in the log:
Slim::Utils::Timers::__ANON__ (272) Error: Timer Plugins::DenonAvpControl::Plugin::handleSendPowerOn failed:

**Comment by SamInPgh** [comment] 2022-09-06 14:15
I was able to recreate the problem and it appears to be a longstanding one, caused by LMS calling the plugin with a "power on" notification for the synced player, which we should ignore. Thank you for the clear description. In my case, it was easily circumvented by simply restarting playback. Is that your experience also? If so, I will proceed with creating a fix for the next plugin release. Thanks again for reporting this.

**Comment by SamInPgh** [comment] 2022-09-06 16:19
If you feel comfortable testing an interim fix, I have attached an updated copy of "Plugin.pm" which can be copied to the DenonAvpControl plugin directory in your LMS installation after renaming the old one to something like Plugin.pm.save. After copying it, you must restart LMS in order to activate it. I would appreciate your feedback on any other issues you run into with the plugin, whether related to this probem or not. Are you aware of the user forum for the plugin? It is the preferred place to report problems rather than here in Github. The link is [here](https://forums.slimdevices.com/showthread.php?60114-Announce-Denon-AVP-Control-Plugin).  

NOTE: Github forced me to add '.txt' to the filename in order to upload it. You must rename it to "Plugin.pm" when copying to the DenonAvpControl plugin directory.

[Plugin.pm.txt](https://github.com/aesculus/denonavpcontrol/files/9498802/Plugin.pm.txt)

**Comment by bjarteskogoy** [comment] 2022-09-06 21:30
Not aware of the forum.
The fix seems to solve the problem!

Reestarting playback would help, but it stopped when changing to the next item on the playlist.

**Comment by bjarteskogoy** [comment] 2022-09-07 07:05
> > Restarting playback would help, but it stopped when changing to the next item on the playlist.
> 
> I'm not sure what you mean by this. Is there still a problem or is this just an observation?

That was just an observation, prior to the fix.

**Comment by SamInPgh** [comment] 2022-09-08 18:10
The fix will be in the next release of the plugin.

**Closed by SamInPgh** 2022-09-08 18:10 UTC

**Comment by SamInPgh** [comment] 2022-10-02 21:41
Fixed in v4.6.3.
